# Generated by Django 6.0.1 on 2026-04-10 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
