# Generated by Django 6.0.1 on 2026-04-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0005_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainmenu",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
